// QueryEngine - core conversation loop

pub mod abort_helpers;
pub use abort_helpers::{cleanup_orphan_tool_uses, wait_for_abort};
pub mod cost_tracker;
pub mod error_handling;
pub mod git_info;
pub mod memory;
pub mod query_engine;
pub mod shared_session;
pub mod task_manager;
pub mod transcript;
pub mod evolution;
pub mod cron;
pub mod projects;
pub mod file_cache;
pub mod session_memory;
pub mod session_persistence;
pub mod token_counter;
pub mod tool_result_store;
pub mod security;
pub mod cross_session_db;
pub mod user_profile;
pub mod tool_health;
pub mod intent_predictor;
pub mod warmup;
pub mod context_allocator;
pub mod sandbox;
// Legacy sandbox types from sandbox_legacy.rs
pub mod sandbox_legacy;
pub mod prompt_injection;
pub mod subagent_policy;
pub mod streaming_executor;
pub mod export;
pub mod spec_engine;
pub mod hooks;
pub mod team;
pub mod template;
pub mod telemetry;
pub mod model_router;
pub mod git_integration;
pub mod permission_gate;
